-- Port av "Amund Theme" fra VSCode (VS2019 Dark base + mørkere flater).
-- Kilde: ~/.vscode-insiders/extensions/amundfremming.amund-theme-0.0.1

local p = {
	bg         = "#0B0D12",
	bg_dark    = "#07090D",
	bg_panel   = "#090B10",
	bg_sel     = "#121825",
	bg_visual  = "#264F78",
	bg_line    = "#12151C",
	border     = "#1C2330",

	fg         = "#D4D4D4",
	fg_dim     = "#858585",
	fg_bright  = "#C6C6C6",
	gray       = "#808080",
	label      = "#C8C8C8",
	indent     = "#404040",

	comment    = "#6A9955",
	doc        = "#608B4E",
	keyword    = "#569CD6",
	control    = "#C586C0",
	string     = "#CE9178",
	number     = "#B5CEA8",
	func       = "#DCDCAA",
	type       = "#4EC9B0",
	interface  = "#B8D7A3",
	struct     = "#86C691",
	variable   = "#9CDCFE",
	escape     = "#D7BA7D",
	regexp     = "#D16969",
	red        = "#F44747",
	blue_soft  = "#6796E6",
	purple_dim = "#646695",
}

vim.cmd.highlight("clear")
vim.g.colors_name = "amund"
vim.o.background = "dark"

local hl = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end

local groups = {
	-- Editor UI
	Normal       = { fg = p.fg, bg = p.bg },
	NormalNC     = { fg = p.fg, bg = p.bg },
	NormalFloat  = { fg = p.fg, bg = p.bg_panel },
	FloatBorder  = { fg = p.border, bg = p.bg_panel },
	FloatTitle   = { fg = p.fg_bright, bg = p.bg_panel, bold = true },
	Cursor       = { fg = p.bg, bg = "#AEAFAD" },
	CursorLine   = { bg = p.bg_line },
	CursorLineNr = { fg = p.fg_bright },
	LineNr       = { fg = p.fg_dim },
	SignColumn   = { bg = p.bg },
	ColorColumn  = { bg = p.bg_panel },
	Visual       = { bg = p.bg_visual },
	Search       = { fg = p.fg, bg = "#623315" },
	IncSearch    = { fg = p.bg, bg = p.escape },
	CurSearch    = { fg = p.bg, bg = p.escape },
	MatchParen   = { fg = p.escape, bold = true },
	Whitespace   = { fg = p.indent },
	NonText      = { fg = p.indent },
	VertSplit    = { fg = p.border },
	WinSeparator = { fg = p.border },
	StatusLine   = { fg = p.fg, bg = p.bg_dark },
	StatusLineNC = { fg = p.fg_dim, bg = p.bg_dark },
	TabLine      = { fg = p.fg_dim, bg = p.bg_panel },
	TabLineSel   = { fg = p.fg, bg = p.bg },
	TabLineFill  = { bg = p.bg_dark },
	Pmenu        = { fg = p.fg, bg = p.bg_panel },
	PmenuSel     = { fg = p.fg, bg = p.bg_sel },
	PmenuSbar    = { bg = p.bg_panel },
	PmenuThumb   = { bg = p.border },
	WildMenu     = { fg = p.fg, bg = p.bg_sel },
	Folded       = { fg = p.fg_dim, bg = p.bg_panel },
	Directory    = { fg = p.variable },
	Title        = { fg = p.keyword, bold = true },
	Question     = { fg = p.number },
	MoreMsg      = { fg = p.number },
	ErrorMsg     = { fg = p.red },
	WarningMsg   = { fg = p.escape },
	Conceal      = { fg = p.gray },
	QuickFixLine = { bg = p.bg_sel },
	Winbar       = { fg = p.fg_dim, bg = p.bg },
	WinbarNC     = { fg = p.fg_dim, bg = p.bg },

	-- Klassiske syntaksgrupper
	Comment        = { fg = p.comment },
	Constant       = { fg = p.keyword },
	String         = { fg = p.string },
	Character      = { fg = p.string },
	Number         = { fg = p.number },
	Boolean        = { fg = p.keyword },
	Float          = { fg = p.number },
	Identifier     = { fg = p.variable },
	Function       = { fg = p.func },
	Statement      = { fg = p.control },
	Conditional    = { fg = p.control },
	Repeat         = { fg = p.control },
	Label          = { fg = p.control },
	Operator       = { fg = p.fg },
	Keyword        = { fg = p.keyword },
	Exception      = { fg = p.control },
	PreProc        = { fg = p.keyword },
	Include        = { fg = p.control },
	Define         = { fg = p.keyword },
	Macro          = { fg = p.keyword },
	Type           = { fg = p.type },
	StorageClass   = { fg = p.keyword },
	Structure      = { fg = p.struct },
	Typedef        = { fg = p.type },
	Special        = { fg = p.escape },
	SpecialChar    = { fg = p.escape },
	Delimiter      = { fg = p.fg },
	Todo           = { fg = p.bg, bg = p.escape, bold = true },
	Error          = { fg = p.red },
	Underlined     = { underline = true },

	-- Treesitter
	["@comment"]              = { fg = p.comment },
	["@comment.documentation"] = { fg = p.doc },
	["@keyword"]              = { fg = p.keyword },
	["@keyword.function"]     = { fg = p.keyword },
	["@keyword.operator"]     = { fg = p.keyword },
	["@keyword.return"]       = { fg = p.control },
	["@keyword.conditional"]  = { fg = p.control },
	["@keyword.repeat"]       = { fg = p.control },
	["@keyword.exception"]    = { fg = p.control },
	["@keyword.import"]       = { fg = p.control },
	["@keyword.coroutine"]    = { fg = p.control },
	["@conditional"]          = { fg = p.control },
	["@repeat"]               = { fg = p.control },
	["@exception"]            = { fg = p.control },
	["@include"]              = { fg = p.control },
	["@string"]               = { fg = p.string },
	["@string.escape"]        = { fg = p.escape },
	["@string.regexp"]        = { fg = p.regexp },
	["@string.special"]       = { fg = p.escape },
	["@character"]            = { fg = p.string },
	["@character.special"]    = { fg = p.escape },
	["@number"]               = { fg = p.number },
	["@number.float"]         = { fg = p.number },
	["@boolean"]              = { fg = p.keyword },
	["@constant"]             = { fg = p.fg },
	["@constant.builtin"]     = { fg = p.keyword },
	["@constant.macro"]       = { fg = p.keyword },
	["@variable"]             = { fg = p.variable },
	["@variable.builtin"]     = { fg = p.keyword },
	["@variable.parameter"]   = { fg = p.variable },
	["@variable.member"]      = { fg = p.fg },
	["@parameter"]            = { fg = p.variable },
	["@field"]                = { fg = p.fg },
	["@property"]             = { fg = p.fg },
	["@function"]             = { fg = p.func },
	["@function.builtin"]     = { fg = p.func },
	["@function.call"]        = { fg = p.func },
	["@function.macro"]       = { fg = p.func },
	["@function.method"]      = { fg = p.func },
	["@function.method.call"] = { fg = p.func },
	["@constructor"]          = { fg = p.type },
	["@type"]                 = { fg = p.type },
	["@type.builtin"]         = { fg = p.keyword },
	["@type.definition"]      = { fg = p.type },
	["@type.qualifier"]       = { fg = p.keyword },
	["@attribute"]            = { fg = p.type },
	["@module"]               = { fg = p.fg },
	["@namespace"]            = { fg = p.fg },
	["@label"]                = { fg = p.label },
	["@operator"]             = { fg = p.fg },
	["@punctuation"]          = { fg = p.fg },
	["@punctuation.bracket"]  = { fg = p.fg },
	["@punctuation.delimiter"] = { fg = p.fg },
	["@punctuation.special"]  = { fg = p.keyword },
	["@tag"]                  = { fg = p.keyword },
	["@tag.attribute"]        = { fg = p.variable },
	["@tag.delimiter"]        = { fg = p.gray },
	["@markup.heading"]       = { fg = p.keyword, bold = true },
	["@markup.strong"]        = { bold = true },
	["@markup.italic"]        = { italic = true },
	["@markup.link"]          = { fg = p.blue_soft },
	["@markup.raw"]           = { fg = p.string },
	["@markup.list"]          = { fg = p.blue_soft },
	["@markup.quote"]         = { fg = p.comment },
	["@diff.plus"]            = { fg = p.number },
	["@diff.minus"]           = { fg = p.string },

	-- LSP semantic tokens: dette er det som gjør at C#/Rust ser ut som i VS
	["@lsp.type.class"]         = { fg = p.type },
	["@lsp.type.interface"]     = { fg = p.interface },
	["@lsp.type.enum"]          = { fg = p.interface },
	["@lsp.type.typeParameter"] = { fg = p.interface },
	["@lsp.type.struct"]        = { fg = p.struct },
	["@lsp.type.type"]          = { fg = p.type },
	["@lsp.type.namespace"]     = { fg = p.fg },
	["@lsp.type.enumMember"]    = { fg = p.fg },
	["@lsp.type.property"]      = { fg = p.fg },
	["@lsp.type.field"]         = { fg = p.fg },
	["@lsp.type.variable"]      = { fg = p.variable },
	["@lsp.type.parameter"]     = { fg = p.variable },
	["@lsp.type.function"]      = { fg = p.func },
	["@lsp.type.method"]        = { fg = p.func },
	["@lsp.type.macro"]         = { fg = p.keyword },
	["@lsp.type.keyword"]       = { fg = p.keyword },
	["@lsp.type.comment"]       = { fg = p.comment },
	["@lsp.type.string"]        = { fg = p.string },
	["@lsp.type.number"]        = { fg = p.number },
	["@lsp.type.operator"]      = { fg = p.fg },
	["@lsp.type.decorator"]     = { fg = p.func },
	["@lsp.type.lifetime"]      = { fg = p.keyword },
	["@lsp.type.selfKeyword"]   = { fg = p.keyword },
	["@lsp.type.builtinType"]   = { fg = p.keyword },
	["@lsp.mod.readonly"]       = {},
	["@lsp.mod.static"]         = {},

	-- Diagnostikk
	DiagnosticError          = { fg = p.red },
	DiagnosticWarn           = { fg = p.escape },
	DiagnosticInfo           = { fg = p.blue_soft },
	DiagnosticHint           = { fg = p.type },
	DiagnosticUnderlineError = { undercurl = true, sp = p.red },
	DiagnosticUnderlineWarn  = { undercurl = true, sp = p.escape },
	DiagnosticUnderlineInfo  = { undercurl = true, sp = p.blue_soft },
	DiagnosticUnderlineHint  = { undercurl = true, sp = p.type },
	DiagnosticVirtualTextError = { fg = p.red, bg = p.bg_line },
	DiagnosticVirtualTextWarn  = { fg = p.escape, bg = p.bg_line },

	-- LSP referanser
	LspReferenceText  = { bg = p.bg_sel },
	LspReferenceRead  = { bg = p.bg_sel },
	LspReferenceWrite = { bg = p.bg_sel },
	LspInlayHint      = { fg = p.purple_dim, bg = p.bg_line },

	-- Diff / git
	DiffAdd    = { bg = "#12261A" },
	DiffChange = { bg = "#121B26" },
	DiffDelete = { bg = "#26141A" },
	DiffText   = { bg = "#1E3352" },
	Added      = { fg = p.number },
	Changed    = { fg = p.keyword },
	Removed    = { fg = p.string },

	-- Telescope
	TelescopeNormal       = { fg = p.fg, bg = p.bg_panel },
	TelescopeBorder       = { fg = p.border, bg = p.bg_panel },
	TelescopePromptNormal = { fg = p.fg, bg = p.bg_sel },
	TelescopePromptBorder = { fg = p.bg_sel, bg = p.bg_sel },
	TelescopePromptTitle  = { fg = p.bg, bg = p.func },
	TelescopeResultsTitle = { fg = p.bg_panel, bg = p.bg_panel },
	TelescopePreviewTitle = { fg = p.bg, bg = p.type },
	TelescopeSelection    = { fg = p.fg, bg = p.bg_sel },
	TelescopeMatching     = { fg = p.func, bold = true },

	-- nvim-cmp
	CmpItemAbbr           = { fg = p.fg },
	CmpItemAbbrDeprecated = { fg = p.gray, strikethrough = true },
	CmpItemAbbrMatch      = { fg = p.keyword, bold = true },
	CmpItemAbbrMatchFuzzy = { fg = p.keyword },
	CmpItemKindFunction   = { fg = p.func },
	CmpItemKindMethod     = { fg = p.func },
	CmpItemKindVariable   = { fg = p.variable },
	CmpItemKindField      = { fg = p.fg },
	CmpItemKindClass      = { fg = p.type },
	CmpItemKindInterface  = { fg = p.interface },
	CmpItemKindStruct     = { fg = p.struct },
	CmpItemKindKeyword    = { fg = p.keyword },
	CmpItemKindText       = { fg = p.fg },
	CmpItemKindSnippet    = { fg = p.escape },
	CmpItemMenu           = { fg = p.gray },
}

for group, opts in pairs(groups) do
	hl(group, opts)
end

-- Terminalfarger
vim.g.terminal_color_0  = p.bg_dark
vim.g.terminal_color_1  = p.red
vim.g.terminal_color_2  = p.number
vim.g.terminal_color_3  = p.escape
vim.g.terminal_color_4  = p.keyword
vim.g.terminal_color_5  = p.control
vim.g.terminal_color_6  = p.type
vim.g.terminal_color_7  = p.fg
vim.g.terminal_color_8  = p.gray
vim.g.terminal_color_9  = p.red
vim.g.terminal_color_10 = p.number
vim.g.terminal_color_11 = p.escape
vim.g.terminal_color_12 = p.blue_soft
vim.g.terminal_color_13 = p.control
vim.g.terminal_color_14 = p.type
vim.g.terminal_color_15 = "#FFFFFF"
